config/routes.rb
Dashing::Application.routes.draw do
  get "sessions/new"

  resources :users
  resources :sessions,  :only => [:new, :create, :destroy]
  resources :items do
    member do
      get :get_file
    end
  end

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/about',   :to => 'pages#about'

  root :to => 'pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_item_form.html.erb
<div class="item_form">
<%= form_for @item, :html => { :multipart => true} do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label 'file', 'Select File' %>:
    <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.label 'shared', 'Share' %>:
    <%= f.check_box :shared %>
  </div>
  <div class="actions">
    <%= f.submit "Upload" %>
  </div>
<% end %>
</div>

app/views/shared/_sign_in_form.html.erb
<h1>Sign in</h1>

<%= form_for(:session, :url => sessions_path) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Sign in" %>
  </div>
<% end %>
<% if User.all.empty? %>
<p>New user? <%= link_to "Sign up now!", signup_path %></p>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <span class="user_name">
      <%= current_user.name %>
    </span><br />
  </a>
  <span>
    <strong>Private Items</strong> <%= @private_items.count %><br />
    <strong>Shared Items</strong> <%= @shared_items.count %><br />
  </span>
</div>