config/routes.rb
Dashing::Application.routes.draw do
  get "sessions/new"

  resources :users
  resources :sessions,  :only => [:new, :create, :destroy]
  resources :items do
    member do
      get :get_file
    end
  end

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/about',   :to => 'pages#about'

  root :to => 'pages#home'

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id           :integer         not null, primary key
#  private_path :string(255)
#  user_id      :integer
#  shared       :boolean
#  created_at   :datetime
#  updated_at   :datetime
#

class Item < ActiveRecord::Base
  attr_accessor :file
  attr_accessible :shared, :file, :private_path

  belongs_to :user

  validates :user_id, :presence => true
#  validates :shared, :presence => true
  validates :file, :presence => true, :on =>:create

  default_scope :order => 'items.created_at DESC'

  def create
    #set the file path
    set_path
    #save the uploaded file
    file_save
    super
  end

  def destroy
    File.delete(full_path) if File.file?(full_path)
  super
  end

  def file_save
    # write the file
    File.open(full_path, "wb") { |f| f.write(file.read) }
  end

  def set_path
    self.private_path = file.original_filename
  end

  def full_path
    File.join(self.user.share_path,private_path)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate, :only => [:create, :edit, :update, :destroy]
  before_filter :authorized_user, :only => [:edit, :update, :destroy]
  before_filter :shared_item, :only => [:show, :get_file]

  def create
    @private_items = current_user.items.where(:shared => false)
    @shared_items = current_user.items.where(:shared => true)
    @item = current_user.items.build(params[:item])
    if @item.save
      flash[:success] = "Item created!"
      redirect_to root_path
    else
      render 'pages/home'
    end
  end

  def destroy
    @item.destroy
    flash[:success] = "Item deleted."
    redirect_back_or root_path
  end

  def get_file
    @item = Item.find(params[:id])
    send_file @item.full_path
  end

  def show
    @item = Item.find(params[:id])
    @title = @item.private_path
  end

  def edit
    @item = Item.find(params[:id])
    @title = "Edit item"
  end

  def update
    @item = Item.find(params[:id])
    @title = "Edit item"
    if @item.update_attributes(params[:item])
      flash[:success] = "Item updated."
      redirect_to @item
    else
      @title = "Edit item"
      render 'edit'
    end
  end

  private

    def authorized_user
      @item = Item.find(params[:id])
      redirect_to root_path unless current_user?(@item.user)
    end

    def shared_item
      @item = Item.find(params[:id])
      if !@item.shared?
        if !signed_in?
          redirect_to signin_path
        else
          redirect_to root_path unless current_user?(@item.user)
        end
      end
    end
end

app/views/items/_item.html.erb
<% if item.shared? or current_user?(item.user) %>
  <tr>
    <td class="item">
      <span class="title">
        <%= link_to item.private_path,item %></span>
      <span class="timestamp">
        Posted <%= time_ago_in_words(item.created_at) %> ago.
      </span>
    </td>
    <% if current_user?(item.user) %>
      <td>
        <%= link_to "get", :action => :get_file, :controller=>"items", :id =>item%>
        <%= link_to "view", item %>
        <%= link_to "edit", edit_item_path(item) %>
        <%= link_to "delete",
                        item,
                        :method => :delete,
                        :confirm => "You sure?",
                        :title => "Delete #{item.private_path}"
        %>
      </td>
    <% end %>
  </tr>
<%end%>

app/views/items/edit.html.erb
<h1>Edit <%=@item.private_path%></h1>

<%= form_for @item, :html => { :multipart => true} do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label 'shared', 'Share' %>:
    <%= f.check_box :shared %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
  <%= link_to "Delete", @item, :method => :delete,
                               :confirm => "This will delete #{@item.private_path}. Are you sure?",
                               :title => "Delete #{@item.private_path}"
   %>
<% end %>

app/views/items/show.html.erb
<h1>
  <%= link_to @item.private_path, :action => :get_file %>
</h1>
<% if current_user?(@item.user) %>
  <%= link_to "edit", edit_item_path(@item) %>
  <%= link_to "delete",
              @item,
              :method => :delete,
              :confirm => "Are you sure?",
              :title => "Delete #{@item.private_path}"
  %><br/><br/>
  <p>
  <%= File.size(@item.full_path) %> bytes.<br/>
  <%= link_to 'You',@item.user %> posted this item <%= time_ago_in_words(@item.created_at) %> ago.<br/>
  Currently <strong><% if !@item.shared%> not <%end%> being shared</strong>.<br/>
  </p>
<% else %>
  <p>
  <%= File.size(@item.full_path) %> bytes.<br/>
  <%= link_to @item.user.name,@item.user %> posted this <%= time_ago_in_words(@item.created_at) %> ago.<br/>
  </p>
<% end %>